---
title: "Replication of Study 2 by Djärv, Zehr, & Schwarz (2017, Proceedings of Sinn und Bedeutung 21)"
author: "Penny Pan"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

Djärv et al. (2017) shows cognitive and emotive factives differ in the entailment of the presupposed content. Specifically, cognitive factives, such as *realize* and *be aware*, entail both the presupposed content in the embedded clause and the attitude/behavior indicated by the predicate. On the other hand, emotive factives, such as *appreciate* and *be happy*, only entail the attitude/behavior. Given a yes/no-continuation acceptability judgement task, the participant rated the *yes, although...* continuation to be more natural for a question with an emotive factive than for a question that contains a cognitive factive.

(Examples from the original paper)

John was happy that his parents are coming to twon, although it turned out he was in fact mistaken/although it turned out that they had to cancel. (Both felicitous).

?? John discovered that his parents are coming to twon, although it turned out he was in fact mistaken/although it turned out that they had to cancel. (Not acceptable as they lead to contradiction).



### Foreseeable Challenge

The link to the experiment is not available, as it was hosted on the older version of the Ibex Farm. Hence, I may have to contact the authors to obtain the stimuli set. Also, I am not sure about the study design--based on the Materials section in the original paper, it seems like each critical item was used four times (one for each combination of predicate and response type), but each filler item was only used once. I would like to confirm this with the authors of the original paper.

[Link to the project repository](https://github.com/psych251/Djarv2017)

[Link to the original paper](https://semanticsarchive.net/Archive/DRjNjViN/DjaervZehrSchwarz.pdf)


## Methods

### Power Analysis

<!-- Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size. Considerations of feasibility for selecting planned sample size. -->

### Planned Sample

<!--Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any. -->
Plannded sample size (2.5 times the original sample size?) All participants are native English speakers.

### Materials

Each stimulus in the experiment consisted of one question and one response. The response was either in the form *yes, although...*, which first provides an affirmation and then denies the content of the embedded content, or in the form *no, because...*, which directly provides a negative response, as shown in (1) and (2), respectively. 


__(1) Yes-response block__

Q: \{Is Maria aware/happy\} that [Mike is moving back to Chicago]?

A: Yes, although he isn't.

__(2) No-response block__

Q: \{Is Maria aware/Is Maria happy\} that [Mike is moving back to Chicago]?

A: No, because he isn't.


In the original study, 24 items were used as the embedded content, and each item was paired with both types of predicates (cognitive and emotive) and both types of responses (*yes, although...* or *no, because...*), resulted in four variations for each item. The authors also controlled the syntactic category of these predicates, resulted in the same number of verbal and adjectival factives.

In addition, 48 filler items were also included to elicit the baseline rating for the yes/no responses. Non-factive predicates, such as *think*, were used the baseline for *yes*, where yes-continuation would acceptable but not the no-continuation (Example 3). On the other hand, questions with two conjunctions were used as baseline for *no*, where the only felicitous response would be the no-continuation (Example 4). 

All items were divided into two blocks based on the answer type. Both the order of the blocks and the order of sentence pairs within each block were randomized.

__(3) *yes*-response baseline/ceiling__

Q. Does Sue think that Bill’s parents are going to the wedding?

A1. \#No, because they are. (infelicitous, "Bad control")

A2. Yes, although they aren’t. (acceptable, "Good control")


__(4) *no*-response baseline/ceiling__

Q. Is John going to Paris and Rome this summer?

A1. No, he's not. (acceptable, "Good control")

A2. \#Yes, although he isn't going to Rome. (infelicitous, "Bad control")

### Procedure	

Each participant saw 144 pairs of question and answer, including 96 critical pairs and 48 filler pairs, and was asked to rate the naturalness of each answer based on a Likert scale, with 1 being "completely unnatural" to 7 being "completely natural." 

### Analysis Plan

<!--Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible. -->

The authors used linear mixed effects regression models to analyze the ratings of the critical pairs. Specifically, they included the predicate type and the answer type as fixed effects. Then, the considered three models, one with the additional main effect of syntactic category, one with the effect of block order, and one simple model with neither of the two. The complex model with all four factors did not converge, and thus was not used. They "tested for the maximally complex models, including all possible interactions of predictors and all random slopes for participants and items as random effects, and (their) different baselines exhausted the logical space of effects and interactions" (p.13).

The simple model, which is the one that only includes the main effects of answer type and predicate type and the interaction effect, is the key model. According to the analyses in the original paper, adding the two additional factors did not significantly change the results. But more importantly, because we do not predicate that neither the block order nor the syntactic category of the predicate should affect the entailment of the embedded content, these factors should not be included as main effects. 

(Why can't we include block order and syntactic category as random effects?)

<!-- You can also pre-specify additional analyses you plan to do.-->

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
